### ISSUE TITLE
Intermittent ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by Jauwaad** [lasselukkari/aWOT#89] opened 2020-12-19 05:36 UTC
Both version 1 and version 3 end up having this error on an Arduino MKR WiFi 1010. This error is very intermittent.

**Comment by lasselukkari** [comment] 2020-12-19 06:45
Please post an example sketch that that can be used to reproduce the error.

**Comment by lasselukkari** [comment] 2020-12-19 06:56
Most likely the same problems as in your other issue. Try explicitly closing the connection.

**Comment by Jauwaad** [comment] 2020-12-20 06:15
Closing the connection does not resolve this issue. It looks like the file download is interrupted. 
<img width="1201" alt="Screen Shot 2020-12-19 at 10 14 26 PM" src="https://user-images.githubusercontent.com/15346540/102706533-954e9b00-4247-11eb-8552-3a2dd1582857.png">

**Comment by lasselukkari** [comment] 2020-12-20 06:54
Could you please attach the project source code so I can see what is going wrong. It seems that for some reason your body has a different size than your headers say it would be.

**Comment by lasselukkari** [comment] 2020-12-20 07:31
It seems that the WiFi library you are using does not implement proper flushing:
https://github.com/arduino-libraries/WiFiNINA/blob/master/src/WiFiClient.cpp#L259-L261

Try adding `delay(1000);` before you disconnect the client. If that makes it reliable gradually reduce the delay to a smaller number,

**Comment by lasselukkari** [comment] 2020-12-20 08:01
According to the github issues of the WiFI library there has been a lot of issues in the past. What firmware version you have installed for the wifi module?

**Comment by lasselukkari** [comment] 2020-12-20 08:02
See: https://github.com/arduino/nina-fw/issues/48

**Comment by Jauwaad** [comment] 2020-12-20 19:09
Apologize for making this hard. Still trying to figure this out. Adding a delay didn't resolve the issue. Using the latest firmware version 1.3.0.

**Comment by lasselukkari** [comment] 2020-12-20 21:37
So is it always the same file? Does it work with curl? Could you record the traffic with wireshark?

**Comment by Jauwaad** [comment] 2020-12-21 03:11
I updated the NINA firmware to 1.4.1. Same error continues. Curl gives the following error assuming an error occurs retrieving the larger file

curl 'http://192.168.86.41/static/js/2.cb5a9df6.chunk.js' -v --output -
.
.
.

??<%??6*h?&
* transfer closed with 81842 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 81842 bytes remaining to read

The source code has some proprietary information. I will try to zip up the general contents and send it over. After which I'll troubleshoot using wireshark.

**Comment by lasselukkari** [comment] 2020-12-21 06:25
The gemerated StaticFiles.h is enough for me.

**Comment by Jauwaad** [comment] 2020-12-21 06:30
See attached

**Comment by Jauwaad** [comment] 2020-12-21 06:31
See attached


[StaticFiles.h.zip](https://github.com/lasselukkari/aWOT/files/5722640/StaticFiles.h.zip)

**Comment by lasselukkari** [comment] 2020-12-21 08:56
I tested the file with ESP8266 and everything works as expected. 

Especially as the problem happens intermittently and during the response writing it starts to sound like that the problem is somewhere in the WiFiNINA stack. I just ordered the board so I can try it out. I expect it to take until next week to arrive because of the holidays.

I have attached the sketch I tested with the esp8266. Could you try it to make sure that the problem still persists with this so that we can be sure the problems is not somewhere else in your code.

[TestServer.zip](https://github.com/lasselukkari/aWOT/files/5723305/TestServer.zip)

**Comment by Jauwaad** [comment] 2020-12-21 20:08
Same issue persists with the TestServer. I added client.stop after processing and a get call to /api/connection. 

In addition, occasionally I got the following error which I didn't get previously

GET http://192.168.86.41/static/js/2.cb5a9df6.chunk.js net::ERR_CONTENT_DECODING_FAILED 200 (OK)

**Comment by lasselukkari** [comment] 2020-12-21 21:42
Could you change your code to have this and see if the library itself detects the error.
```
void loop() {
  WiFiClient client = server.available();

  if (client.connected()) {
    app.process(&client);
    if(client.getWriteError()){
      Serial.println("Client failed to write");
    }
    client.stop();
  }
}
```

I have never seen the writes to fail with any other hardware combination so there has been no reason trying to detect them in any way.

My MKR WiFi 1010 board is on it's way. I should get it before the weekend.

**Comment by Jauwaad** [comment] 2020-12-21 22:08
Yes. It reported client failed to write.

**Comment by lasselukkari** [comment] 2020-12-21 22:29
Maybe making the write buffer smaller (or bigger) could help. Try changing this value here: https://github.com/lasselukkari/aWOT/blob/master/src/aWOT.h#L59. You can start with some really small value and if works try increasing it until it starts to fail again. I will try dig in to the firmware code and see what are the possible error cases.

**Comment by Jauwaad** [comment] 2020-12-21 22:48
The error occurs on both ends. The larger buffers end up getting more
errors.

**Comment by lasselukkari** [comment] 2020-12-21 23:14
I took a look at the firmare https://github.com/arduino/nina-fw. I did not realise it is built using the ESP32 Arduino core. The  core files bundled with the project are rather outdated and seem to be maintained and modified manually. You can comapre the edit times between https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi/src and https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi/src. Also the ESP-IDF dates back to a year ago.

Considering how unstable the ESP32 Arduino core has been so far I'm not really surprised that we see these problems.

To be honest my advice would be to stay away from this software/hardware stack combination. It's a mess. I will try to see if there is something I can do once I receive the board but I would seriously reconsider the options.

**Comment by Jauwaad** [comment] 2020-12-21 23:21
Thank you for your response. We’re tied to the MKRWifi 1010, any
suggestions on the choice of library is appreciated. Everything else works
perfectly. We are using WiFi for other communication over tcp and not
seeing any data drops. TCP communications are in binary and continuous and
fast. This leads me to think that there is something in the aWOT code that
doesn’t work well with the board

**Comment by lasselukkari** [comment] 2020-12-22 00:44
The aWOT library uses the Stream class for reading and writing ([aWOT.h#L257](https://github.com/lasselukkari/aWOT/blob/master/src/aWOT.h#L257)). 

The Stream class is a base class that is extended by the various WiFi and Ethernet libraries. Serial ports are also Streams as well as the SD card file instances and so on. This means that aWOT codebase is almost hardware agnostic. You can even type in the HTTP requests using the serial monitor if you add `if (Serial.available()) {app.process(&Serial);}` to your loop. At the point where our problems happen the library just does just simple writes. There is really no way to use the Stream write functions in a "wrong" way so that it sometimes works and sometimes doesn't.

Have you been running a tcp server previously? I can see that just running a client is a lot less error prone. I believe we can most likely reproduce the behavior by emulating the same writes to a connected client without using the aWOT library. Maybe that way it would be easier to find the limitation we hitting now.

**Comment by Jauwaad** [comment] 2020-12-22 00:52
I am running two instances of a TCP server along with the Webserver running
using aWOT. The communication is less forgiving on the binary protocols and
I don’t see any errors running it continuously for days.

**Comment by lasselukkari** [comment] 2020-12-22 00:57
Does the error ever happen with smallest files?

**Comment by Jauwaad** [comment] 2020-12-22 00:58
No, it doesn't.

**Comment by lasselukkari** [comment] 2020-12-22 01:08
You could try to add some artificial delay() before this line: https://github.com/lasselukkari/aWOT/blob/master/src/aWOT.cpp#L162
and maybe before this one too:
https://github.com/lasselukkari/aWOT/blob/master/src/aWOT.cpp#L188

This would limit the frequency we call the write api that goes through rather inefficient SPI protocol to the ESP32 running an outdated software with tons of know bugs unfixed trying to juggle with all the open connections while keeping the wifi connection working at the same time. Maybe the poor thing would not get exhausted anymore.

**Comment by Jauwaad** [comment] 2020-12-22 02:07
I added from 1 - 20ms delays before and after. The error still popped up.

**Comment by lasselukkari** [comment] 2020-12-22 10:18
Someone else seems to have the same problem here: https://github.com/arduino-libraries/WiFiNINA/issues/129

**Comment by lasselukkari** [comment] 2020-12-22 21:11
The board arrived today. That was faster than I expected. I made the order under 24 hours ago and it came from another city.

Here is sketch that has been modified from the [WiFiNINA WiFiWebServer](https://github.com/arduino-libraries/WiFiNINA/blob/master/examples/WiFiWebServer/WiFiWebServer.ino) example.

```cpp
#include <SPI.h>
#include <WiFiNINA.h>

#define WIFI_SSID ""
#define WIFI_PASSWORD ""

WiFiServer server(80);

void setup() {
  Serial.begin(9600);

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println(WiFi.localIP());

  server.begin();
}

void loop() {
  // listen for incoming clients
  WiFiClient client = server.available();
  if (client) {
    Serial.println("new client");
    // an http request ends with a blank line
    boolean currentLineIsBlank = true;
    while (client.connected()) {
      if (client.available()) {
        char c = client.read();
        // if you've gotten to the end of the line (received a newline
        // character) and the line is blank, the http request has ended,
        // so you can send a reply
        if (c == '\n' && currentLineIsBlank) {
          // send a standard http response header
          client.println("HTTP/1.1 200 OK");
          client.println("Content-Type: text/plain");
          client.println("Content-Length: 10000");
          client.println("Connection: close");  // the connection will be closed after completion of the response
          client.println();
          for (int i = 0; i < 10; i++) {
            client.print(
              "****************************************************************************************************"
              "****************************************************************************************************"
              "****************************************************************************************************"
              "****************************************************************************************************"
              "****************************************************************************************************"
              "****************************************************************************************************"
              "****************************************************************************************************"
              "****************************************************************************************************"
              "****************************************************************************************************"
              "****************************************************************************************************"
            );
          }

          break;
        }
        if (c == '\n') {
          // you're starting a new line
          currentLineIsBlank = true;
        } else if (c != '\r') {
          // you've gotten a character on the current line
          currentLineIsBlank = false;
        }
      }
    }


    if (client.getWriteError()) {
      Serial.println("Client write error detected");
    }
    
    // give the web browser time to receive the data
    delay(1);
    client.stop();
  }
}
```

With a few browser reloads I was able to reproduce the same behaviour you are seeing.

<img width="612" alt="Screenshot 2020-12-22 at 22 48 43" src="https://user-images.githubusercontent.com/1687972/102933331-c11d8b00-44aa-11eb-9e4d-2a5d08a2f891.png">

 I think this discussion needs to be moved to the WiFiNINA repository because the problem is not in this library.

**Comment by lasselukkari** [comment] 2020-12-22 21:23
What buffer sizes did you actually try? I see that with 10 it seems to work reliably but it's really slow because it's writing so small chunks.

**Comment by lasselukkari** [comment] 2020-12-26 18:31
I'm closing this issue because the problem is not in this library. Let's continue the discussion in the nina-fm repository.

**Closed by lasselukkari** 2020-12-26 18:31 UTC

**Comment by lasselukkari** [comment] 2021-01-07 17:04
The bug is fixed once these get merged and released:
https://github.com/arduino-libraries/WiFiNINA/pull/146
https://github.com/arduino/nina-fw/pull/62

**Comment by Jauwaad** [comment] 2021-01-07 17:30
Thanks a lot. Were you able to test it out. Looking forward to the release

**Comment by lasselukkari** [comment] 2021-01-07 17:33
Yes i tested it with your StaticFiles.h and it works fine now. I just need to figure out some fun project for the board I bought for testing this :).
